### ISSUE TITLE
Tag view does not work

### ISSUE THREAD

**Issue by isaaclo123** [carnager/buku_run#12]
I have tags in my bookmarks

![2017-06-09-134702_1366x768_scrot](https://user-images.githubusercontent.com/9246180/26993944-3a5ccea4-4d1a-11e7-83ea-f9e6380ebf4a.png)

But tag view only shows a blank menu

![2017-06-09-134715_1366x768_scrot](https://user-images.githubusercontent.com/9246180/26993958-4bbdc310-4d1a-11e7-9af1-7288a3bf943d.png)

**Comment by carnager** [comment]
hmm, cannot reproduce. 

```
buku --np --st | awk '{$NF=""; print $0}' | cut -d ' ' -f2-
```

**Comment by isaaclo123** [comment]
It seems in my version of buku, --np does not work, but --noprompt does. Ill make a pull request

**Comment by carnager** [comment]
--noprompt does not work in latest buku version. just update your buku

**Comment by isaaclo123** [comment]
Did that. Can this issue be closed now?

**Comment by carnager** [comment]
You tell me. Did it work?

**Comment by isaaclo123** [comment]
Yes :P
