### ISSUE TITLE
rofi -width setting ignored.

### ISSUE THREAD

**Issue by vredesbyyrd** [carnager/buku_run#19]
First, great script. Thanks for sharing. 

I use rofi in -fullscreen mode. And I cant seem to get buku_run to respect the -width argument. Your script has -width set at 1000 by default, but changing it doesnt do anything, width stays the same regardless of the -width argument. I have tried via the local config and also editing the script directly. 

As it is now, when using rofi fullscreen the output of buku_run takes up half the width of the screen.  which cuts off viewing most of the bookmarks url. Since I already use rofi in fullscreen, it seems like wasted real estate.  

I am wondering if the rofi width argument is actually being respected, but there is something else in the script controlling the width of the bookmark url output? I think that might be the case, but reading through your script I cant get a handle on it. As most of it is admittedly over my head.  

Any pointers would be appreciated.

**Comment by carnager** [comment]
See line 3 of the script. This can be overridden in the config file

**Comment by vredesbyyrd** [comment]
Thanks for getting back. I already edited the -width option in $HOME/.config/buku_run/config. Did not have any effect. Hmmmm. I ended up finding a workaround, though I do not no if its an appropriate or clean way to accomplish it, works though. I edited line 44 in the script: 

    content=$(buku -p -f 2 | awk 'NF == 2 { $0 = $0 "NOTAG" }; { $2 = substr($2,0,170); print 
    $1"\t"$2"\t"$3,$4,$5 }' | column -t -s $'\t') 

I changed: 

    { $2 = substr($2,0,60); 
to 
    
    { $2 = substr($2,0,170); 

If I am honest i dont know why it worked, but it did the job....

**Comment by carnager** [comment]
That's more than strange, I just tried and setting width in config file works just fine...

**Comment by vredesbyyrd** [comment]
Hmmm. Strange indeed. 

Okay. I removed the -width parameter completely, has no effect. If you want, here is a link of a few images to clarify what I am talking about. I am not positive we are on the same page regarding how I was expecting the bookmarks to display. Buku_run might be working as expected.  

Both images have the -width parameter removed. One has my "workaround" in it. The third is a rofi search script I use, just as an example of how my other rofi scripts display at fullscreen. As far as I am concerned, all is good after my edit.

And just a note, I normally wouldnt post a pic of my bookmarks online or would at least blur them, but the link will expire and im not worried about you and maybe a few other people seeing them for troubleshooting purposes.  

https://1drv.ms/f/s!Au0J8kZrcsZnjJA1tZZWKgGJ4IG4hw

**Comment by carnager** [comment]
Ah, indeed I was thinking something else. I don't think this can be solved in an elegant way. One could make the width for urls configurable in config I guess.
