### ISSUE TITLE
buku_run doesn't respect my font settings

### ISSUE THREAD

**Issue by Hund** [carnager/buku_run#8]
I use Terminus for Rofi, but buku_run uses Sans or something. I tried adding font settings to the config and trying the `--font` flag, but  nothing works.

What am I doing wrong?

**Comment by carnager** [comment]
font is a rofi setting. you can edit the _rofi function to include something like `-font "Dejavu Sans Mono 12`

**Comment by Hund** [comment]
Oh! I used two dashes. Thanks!
