### ISSUE TITLE
Tags are not working properly

### ISSUE THREAD

**Issue by isaaclo123** [carnager/buku_run#9]
Tags do not work properly in two ways

First, the tag view does not work. switching to the tag view with Alt-Tab results in a "loading..." error screen.

![2017-06-08-212556_1366x768_scrot](https://user-images.githubusercontent.com/9246180/26961117-340a56e0-4c91-11e7-8ec2-6d50070203a1.png)

The tag editing also does not work on entries with "NOTAG"s, resulting in a "loading..." screen as well and not updating the buku entries.

![2017-06-08-212610_1366x768_scrot](https://user-images.githubusercontent.com/9246180/26961116-34065be4-4c91-11e7-916a-775546359fde.png)

**Comment by carnager** [comment]
hmm, seems bukus behavior changed. It uses a pager now to show tags, that's bad news, I will ask what can be done about this.

**Comment by isaaclo123** [comment]
It seems that buku has an argument "--noprompt" that should help out
